version: "3.9"

services:
#  db:
#    image: mysql:8.0
#    container_name: reliance-inno-db
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: rootpassword
#      MYSQL_DATABASE: reliance_inno
#      MYSQL_USER: reliance
#      MYSQL_PASSWORD: reliance_password
#    ports:
#      - "3306:3306"
#    volumes:
#      - mysql_data:/var/lib/mysql

  web:
    container_name: reliance-inno-web
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      DATABASE_URL: mysql://root:yourpassword@77.37.121.56:3306/relianceinno
    restart: always

volumes:
  mysql_data:
